version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility..."
      - choco install zip -y  # Install zip utility using Chocolatey
  build:
    commands:
      - echo "Building the code..."
      - Compress-Archive -Path * -DestinationPath code.zip  # Zip the entire source code directory
artifacts:
  files:
    - code.zip  # Specify the zip file to be stored as an artifact
  discard-paths: yes  # Discard paths to store the zip directly in S3