version: 0.2

phases:
  install:
    commands:
      - echo "Updating the package lists..."

  build:
    commands:
      - echo "Building the code..."
      - echo "Zipping the source code..."
      - zip -r code.zip *  # Zip the entire source code directory, including appspec.yml

artifacts:
  files:
    - appspec.yml  # Ensure appspec.yml is at the top level of the S3 artifact
    - code.zip     # Also upload the code.zip as part of the artifact
  discard-paths: yes  # Discard paths to store the zip directly in S3
