version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.2
    commands:
      - echo "Installing Backend Dependencies..."
      - cd backend
      - npm install

  build:
    commands:
      - echo "Running Backend Build..."
      - npm run build  # This assumes you have a build script in your package.json
      - echo "Zipping Backend Application..."
      - cd ..
      - zip -r backend.zip backend/

artifacts:
  files:
    - backend.zip
  discard-paths: yes
