version: 0.2

phases:
  install:
    commands:
      - echo "Updating the package lists..."

  build:
    commands:
      - echo "Building the code..."
      - zip -r code.zip *  # Zip the entire source code directory

artifacts:
  files:
    - code.zip  # Specify the zip file to be stored as an artifact
  discard-paths: yes  # Discard paths to store the zip directly in S3
