version: 0.2

phases:
  install:
    commands:
      - echo "Updating the package lists..."
      - sudo apt-get update -y  # Update the package list
      - echo "Installing zip utility..."
      - sudo apt-get install zip -y  # Install zip utility
      - echo "Installing Node.js dependencies..."
      - npm install  # Install Node.js dependencies listed in package.json

  build:
    commands:
      - echo "Building the code..."
      - zip -r code.zip *  # Zip the entire source code directory

artifacts:
  files:
    - code.zip  # Specify the zip file to be stored as an artifact
  discard-paths: yes  # Discard paths to store the zip directly in S3
